### ISSUE TITLE
Bug report for tablemeth_nonref.py

### ISSUE THREAD

**Issue by sunyumail93** [adamewing/tldr#12]
Hi, it's me again.

I found one bug in the tablemeth_nonref.py script.
I ran the program using the command:
tablemeth_nonref.py -t Data.table.txt --teont_dir Data_TLDR

And I got the following error:
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

I found this was because the teont_dir parameter was not properly passed to the program:
teont_dir = None
if args.teont_dir is None:
teont_dir = '.'.join(args.table.split('.')[:-2])
...
assert os.path.exists(teont_dir)

I suggest to add:
`    else:`
        `teont_dir=args.teont_dir`
after the if statement, so the program can take the argument when providing the path.

**Comment by sunyumail93** [comment]
BTW, this also happens in the plotmeth_nonref.py when providing -d parameter

**Comment by adamewing** [comment]
Thanks! fixed in e824423.
