### ISSUE TITLE
Choice of consensus sequences in teref.human.fa 

### ISSUE THREAD

**Issue by SegoleneDiry** [adamewing/tldr#2]
Hi Adam,
I'm a beginner in transposable elements analysis in human genome and I'm interested in your tool TLDR. I'm wondering how do you create the teref.human.fa file (from which database or publications)?
Thank you for your help,
Segolene

**Comment by adamewing** [comment]
Hi, there isn't really a database or publication I can point to for the te reference file, for the most part it consists of full length low-divergence examples from the reference genome (from the RepeatMasker track).

**Comment by SegoleneDiry** [comment]
Ok, thanks!
