### ISSUE TITLE
[E::fai_build_core] Format error, unexpected "C" at line 1

### ISSUE THREAD

**Issue by malonematt** [adamewing/tldr#23]
When running tldr with: 
tldr-b /path/to/final.bam -r /path/to/Masked_Genome_061021.fa.fai -o 1217normLength -e none --detail_output --extend_consensus 1000 --procs 16

I run into the error from the title after writing the clusters to the pickle, when it is loading the clusters. 

Is this an issue of how my indexed reference is formatted? That's my only thought so far.

**Comment by malonematt** [comment]
This is the format of my ref.fa.fai: 
CM025008.1	64216774	90	80	81
CM025009.1	74218288	65019664	80	81
CM025010.1	57828929	140165771	80	81
CM025011.1	49614181	198717652	80	81
CM025012.1	49927339	248952101	80	81
CM025013.1	61955777	299503622	80	81
CM025014.1	43216860	362233937	80	81
CM025015.1	57431038	405991098	80	81
CM025016.1	54464365	464140114	80	81
CM025017.1	49825902	519285375	80	81

**Comment by adamewing** [comment]
You're feeding it the index instead of the .fasta, try `-r /path/to/Masked_Genome_061021.fa` instead and let me know if that helps.

**Comment by adamewing** [comment]
closing due to likely resolution
