### ISSUE TITLE
Finding non fully embedded reads

### ISSUE THREAD

**Issue by mmisak** [adamewing/tldr#24]
Hello,

I was wondering whether it is possible to run TLDR in a way, such that it also finds not fully embedded reads. I.e. reads that only support the insertion on one side and then the read ends.

Regarding the "--embed_minreads" parameter, the Readme says "Minimum number of reads completely embedding the insertion (default = 1, requires at least 1)". To my surprise, the program also started running when I tried setting this parameter to 0. (However, the program is running for 5 days already for one sample).

I was wondering: Would this actually give me reads that only support the insertion on one side since the Readme is apparently discouraging doing this?

**Comment by adamewing** [comment]
Hi, Embedded reads are a hard requirement given the way tldr works so the best workaround would probably be to create 'synthetic' reads with embedded TE insertions through assembly, align the contigs and feed them to tldr along with the original .bam. Given that assembly tends to 'collapse' one or the other allele it would be best if this were a haplotype-specific assembly. I don't have suggestions for what tools to use offhand (possibly pepper/deepvariant --> whatshap --> flye or something) but it's something I'd like to investigate in the near future.

**Comment by mmisak** [comment]
Thanks for the detailed reply and thanks for also suggesting PALMER, I'll give it a shot!
