### ISSUE TITLE
Insertion consensus letter-case

### ISSUE THREAD

**Issue by maxfieldk** [adamewing/tldr#35]
Hi Adam,
Thank you for this excellent piece of software. My question pertains to the case-convention followed when writing the insert consensus sequence.
I was expecting to find a single contiguous lower-case region for all inserts. However, I find the following type of situation in many inserts (I've made up the number of bases but directionally this is what I've observed):

Upper case 100 bases
Lower case 100 bases
Upper case 100 bases
Lower case 600 bases
Upper case 100 bases

If I use --color_consensus, the first Lower stretch is colored black, not yellow.

I was initially using the letter case to identify the TE coordinate, but have therefore realized this is not a good bet.
How should I go about extracting the coordinates of the TE insert for the purpose of building a gtf annotation?
I've attached an example photo of the consensus.

![Screenshot 2023-11-15 162212](https://github.com/adamewing/tldr/assets/44215152/a99fe457-aa9b-48a7-b7f7-fd50fcc4c7ea)

Thanks again!

**Comment by adamewing** [comment]
Lower case indicates sequences not aligned to the reference genome, so in general the insertion should be lower case. tldr allows multiple unaligned segments per insertion but they'll only be coloured like that if they match something in the te references. If this is human data my feeling is the example you posted is not a real insertion - should have something in the filter column?
