### ISSUE TITLE
Argument not recognized --max_te_length

### ISSUE THREAD

**Issue by gbdias** [adamewing/tldr#5]
Hi,

When I try changing the default `--max_te_length` for tldr I get the following error:
```
tldr: error: unrecognized arguments: --max_te_length 12000
```

Am I using incorrect syntax?

Thanks!

**Comment by adamewing** [comment]
Hi, the flag should be `--max_te_len`. Let me know if that doesn't work.

**Comment by gbdias** [comment]
Thanks! The error goes away if I use `--max_te_len`

Just a heads up the README currently shows `--max_te_length`.
https://github.com/adamewing/tldr#--max_te_length

**Comment by adamewing** [comment]
Ah, ok thanks, fixed.
