### ISSUE TITLE
Filter field without any 'PASS' flag

### ISSUE THREAD

**Issue by gbdias** [adamewing/tldr#9]
Hi @adamewing,

- I am trying to use tldr on a public _Drosophila melanogaster_ Nanopore dataset generated in this paper: https://www.g3journal.org/content/8/10/3143.short.
- This dataset is ~30x coverage and has the following length distribution.
<img width="856" alt="Screen Shot 2020-12-01 at 11 09 52 AM" src="https://user-images.githubusercontent.com/7614153/100765654-c153ca80-33c5-11eb-8218-8a6c6e8dd4a8.png">

- I used a high quality reference genome from a different _D. mel_ strain as the mapping reference.
https://www.nature.com/articles/s41588-017-0010-y

- My tldr results include over 1000 predictions, but none of them has a 'PASS' flag in the filter field. The flags are listed below.
```
gd98309@ss-sub2 tldr_430029$ cut -f23 iso1_ont_sort.table.txt | sort | uniq -c
      1 Filter
   1087 LeftFlankSize,RightFlankSize,UnmapCoverNA,NoTEAlignment,NonRemappable,ShortIns
      8 LeftFlankSize,RightFlankSize,UnmapCoverNA,NoTEAlignment,NonRemappable,ShortIns,ZeroMapQ
     13 LeftFlankSize,UnmapCoverNA,NoTEAlignment,NonRemappable,ShortIns
      3 LeftFlankSize,UnmapCoverNA,NoTEAlignment,NonRemappable,ShortIns,ZeroMapQ
```
- Do you have any advice on how to treat these predictions that do not pass the filter?

Thanks

**Comment by adamewing** [comment]
Hi, thanks for your interest. This looks a lot like issue #7  which had to do with the formatting of the TE reference .fasta (`-e/--elts`). As of the commit referenced in that issue tldr will enforce the ">Family:Subfamily" formatting. Does that help?
